@extends('layouts.app')

@section('contents')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h2>{{ $report->title }}</h2>
                    <div>
                        <a href="{{ route('reports.edit', $report->id) }}" class="btn btn-warning">
                            <i class="fas fa-edit"></i> Edit Report
                        </a>
                        <a href="{{ route('reports.index') }}" class="btn btn-secondary">
                            <i class="fas fa-arrow-left"></i> Back to Reports
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    @if(session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                    @endif

                    @if(session('info'))
                    <div class="alert alert-info" role="alert">
                        {{ session('info') }}
                    </div>
                    @endif

                    <div class="mb-4">
                        <h4>Report Details</h4>
                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th width="20%">Report Type</th>
                                    <td><span class="badge bg-info">{{ ucfirst($report->report_type) }}</span></td>
                                </tr>
                                <tr>
                                    <th>Generated By</th>
                                    <td>{{ $report->user ? $report->user->name : 'Unknown' }}</td>
                                </tr>
                                <tr>
                                    <th>Report Date</th>
                                    <td>{{ $report->report_date->format('F d, Y') }}</td>
                                </tr>
                                <tr>
                                    <th>Date Range</th>
                                    <td>{{ $report->start_date->format('F d, Y') }} - {{ $report->end_date->format('F d, Y') }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="mb-4">
                        <h4>Parameters</h4>
                        <table class="table table-bordered">
                            <tbody>
                                @if(isset($report->parameters) && count($report->parameters) > 0)
                                @foreach($report->parameters as $key => $value)
                                @if(!empty($value))
                                <tr>
                                    <th width="20%">{{ ucwords(str_replace('_', ' ', $key)) }}</th>
                                    <td>{{ is_bool($value) ? ($value ? 'Yes' : 'No') : $value }}</td>
                                </tr>
                                @endif
                                @endforeach
                                @else
                                <tr>
                                    <td colspan="2">No specific parameters</td>
                                </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>

                    <div class="mb-4">
                        <h4>Report Summary</h4>
                        @if(isset($report->data['summary']))
                        <table class="table table-bordered">
                            <tbody>
                                @foreach($report->data['summary'] as $key => $value)
                                @if(!is_array($value))
                                <tr>
                                    <th width="20%">{{ ucwords(str_replace('_', ' ', $key)) }}</th>
                                    <td>{{ $value }}</td>
                                </tr>
                                @endif
                                @endforeach
                            </tbody>
                        </table>
                        @else
                        <p>No summary data available</p>
                        @endif
                    </div>

                    <div>
                        <h4>Report Data</h4>
                        @if($report->report_type == 'inventory')
                        @include('reports.partials.inventory_data')
                        @elseif($report->report_type == 'purchase_order')
                        @include('reports.partials.purchase_order_data')
                        @elseif($report->report_type == 'issue')
                        @include('reports.partials.issue_data')
                        @elseif($report->report_type == 'supplier')
                        @include('reports.partials.supplier_data')
                        @elseif($report->report_type == 'department')
                        @include('reports.partials.department_data')
                        @else
                        <p>No detailed data available for this report type</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection